version: '2'

services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.2-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=root
      - MARIADB_DATABASE=applaud
      - MARIADB_PASSWORD=secret

  myapp:
    tty: true
    image: docker.io/bitnami/laravel:7-debian-10
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=root
      - DB_DATABASE=applaud
      - DB_PASSWORD=secret
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    # privileged: true # Privileged mode could be required to run this container under Windows
